server:
  port: 9095
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/miniuniversitydb
    username: sa
    password:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/MyUniversity
#    username: me
#    password: me
  liquibase:
    change-log: classpath:databaseChangeLog.xml
  jpa:
    show-sql: true
